name: kibot

on:
  release:
    types: [published]
    # paths:
    # - '**.sch'
    # - '**.kicad_pcb'
  workflow_dispatch:

jobs:
  kibot:
    runs-on: ubuntu-latest
    permissions:
      # Required to modify the release (add assets)
      contents: write
    steps:
    - uses: actions/checkout@v2
    # Sensor
    - uses: INTI-CMNB/KiBot@v2_k9
      with:
        config: ./kicad/sensor/config.kibot.yaml
        dir: ./output/sensor
        schema: ./kicad/sensor/sensor.kicad_sch
        board: ./kicad/sensor/sensor.kicad_pcb
    # Receiver
    - uses: INTI-CMNB/KiBot@v2_k9
      with:
        config: ./kicad/receiver/config.kibot.yaml
        dir: ./output/receiver
        schema: ./kicad/receiver/receiver.kicad_sch
        board: ./kicad/receiver/receiver.kicad_pcb
    # Upload some of the kibot outputs to release
    - name: Upload results to release
      if: ${{ github.event_name == 'release' }}
      uses: softprops/action-gh-release@v2
      with: 
        files: |
          ./output/sensor/pdf/pcb/sensor-assembly.pdf
          ./output/sensor/pdf/schematic/sensor-schematic.pdf
          ./output/receiver/pdf/pcb/receiver-assembly.pdf
          ./output/receiver/pdf/schematic/receiver-schematic.pdf
    - name: upload results
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: sensor output
        path: ./output
